module.exports = {
    tables : [
        //cash 9 seats
        {
            id: 0,
            name : 'Bloody gate',
            seats : 9,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"cash",
            cardSuit:"default",
            cardBack:"red",
            roomBackground: "1",
            roomColor: "#3fff00",
            feltColor: "red",
            chipColor: "normal"

        },
        {
            id: 1,
            name : 'Lordaeron',
            seats : 9,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"cash",
            cardSuit:"default",
            cardBack:"red",
            roomBackground: "4",
            roomColor: "#cfff10",
            feltColor: "red",
            chipColor: "normal"

        },
        {
            id: 2,
            name : 'Bloodtooth',
            seats : 9,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"cash",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "3",
            roomColor: "#a14f49",
            feltColor: "red",
            chipColor: "normal"

        },
        {
            id: 3,
            name : 'Ravenhill',
            seats : 9,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"cash",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "2",
            roomColor: "#ffffff",
            feltColor: "red",
            chipColor: "normal"

        },
        {
            id: 4,
            name : 'Karazhan',
            seats : 9,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"cash",
            cardSuit:"default",
            cardBack:"red",
            roomBackground: "1",
            roomColor: "#a14f49",
            feltColor: "red",
            chipColor: "normal"

        },
        //cash 6 seats
        {
            id: 5,
            name : 'Casterly Rock',
            seats : 6,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"cash",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "5",
            roomColor: "#ffffff",
            feltColor: "red",
            chipColor: "normal"

        },
        {
            id: 6,
            name : 'Terrallende',
            seats : 6,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"cash",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "6",
            roomColor: "#729751",
            feltColor: "red",
            chipColor: "normal"

        },
        {
            id: 7,
            name : 'Moonbrook',
            seats : 6,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"cash",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "6",
            roomColor: "#1000ff",
            feltColor: "red",
            chipColor: "normal"

        },
        {
            id: 8,
            name : 'Death Hollow',
            seats : 6,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"cash",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "2",
            roomColor: "#73727a",
            feltColor: "red",
            chipColor: "normal"

        },
        {
            id: 9,
            name : 'Dreadfort',
            seats : 6,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"cash",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "6",
            roomColor: "#bc2108",
            feltColor: "red",
            chipColor: "normal"

        },
        //SIT `N GO 
        {
            id: 10,
            name : 'Sentinel Hill',
            seats : 3,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 200,
            privateTable: false,
            type:"sit",
            cardSuit:"default",
            cardBack:"red",
            roomBackground: "1",
            roomColor: "#3fff00",
            feltColor: "green",
            chipColor: "normal"

        },
        {
            id: 11,
            name : 'Orgrimmar',
            seats : 3,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 200,
            privateTable: false,
            type:"sit",
            cardSuit:"default",
            cardBack:"red",
            roomBackground: "4",
            roomColor: "#cfff10",
            feltColor: "green",
            chipColor: "normal"

        },
        {
            id: 12,
            name : 'Brackenwall',
            seats : 3,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 200,
            privateTable: false,
            type:"sit",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "3",
            roomColor: "#a14f49",
            feltColor: "green",
            chipColor: "normal"

        },
        {
            id: 13,
            name : 'eyrie',
            seats : 3,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 200,
            privateTable: false,
            type:"sit",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "2",
            roomColor: "#ffffff",
            feltColor: "green",
            chipColor: "normal"

        },
        {
            id: 14,
            name : 'SouthWind',
            seats : 3,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 200,
            privateTable: false,
            type:"sit",
            cardSuit:"default",
            cardBack:"red",
            roomBackground: "1",
            roomColor: "#a14f49",
            feltColor: "green",
            chipColor: "normal"

        },
        //cash 6 seats
        {
            id: 15,
            name : 'Lakeshire',
            seats : 3,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 200,
            privateTable: false,
            type:"sit",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "5",
            roomColor: "#ffffff",
            feltColor: "green",
            chipColor: "normal"

        },
        {
            id: 16,
            name : 'Undermine',
            seats : 3,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 200,
            privateTable: false,
            type:"sit",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "2",
            roomColor: "#804e06",
            
            feltColor: "green",
            chipColor: "normal"

        },
        {
            id: 17,
            name : 'Stormwind',
            seats : 3,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 200,
            privateTable: false,
            type:"sit",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "6",
            roomColor: "#1000ff",
            feltColor: "green",
            chipColor: "normal"

        },
        {
            id: 18,
            name : 'Goldshire',
            seats : 3,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 200,
            privateTable: false,
            type:"sit",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "6",
            roomColor: "#729751",
            feltColor: "green",
            chipColor: "normal"

        },
        {
            id: 19,
            name : 'Starfall',
            seats : 3,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 200,
            privateTable: false,
            type:"sit",
            cardSuit:"inverted",
            cardBack:"red",
            roomBackground: "6",
            roomColor: "#1000ff",
            feltColor: "green",
            chipColor: "normal"

        },
        //tournament
        {
            id: 20,
            name : 'Bloody gate',
            seats : 9,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"tournament",
            cardSuit:"default",
            cardBack:"#0a1a75",
            roomBackground: "1",
            roomColor: "#3fff00",
            feltColor: "#0a1a75",
            chipColor: "normal"

        },
        {
            id: 21,
            name : 'Lordaeron',
            seats : 9,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"tournament",
            cardSuit:"default",
            cardBack:"#0a1a75",
            roomBackground: "4",
            roomColor: "#cfff10",
            feltColor: "#0a1a75",
            chipColor: "normal"

        },
        {
            id: 22,
            name : 'Bloodtooth',
            seats : 9,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"tournament",
            cardSuit:"inverted",
            cardBack:"#0a1a75",
            roomBackground: "3",
            roomColor: "#a14f49",
            feltColor: "#0a1a75",
            chipColor: "normal"

        },
        {
            id: 23,
            name : 'Ravenhill',
            seats : 9,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"tournament",
            cardSuit:"inverted",
            cardBack:"#0a1a75",
            roomBackground: "2",
            roomColor: "#ffffff",
            feltColor: "#0a1a75",
            chipColor: "normal"

        },
        {
            id: 24,
            name : 'Karazhan',
            seats : 9,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"tournament",
            cardSuit:"default",
            cardBack:"#0a1a75",
            roomBackground: "1",
            roomColor: "#a14f49",
            feltColor: "#0a1a75",
            chipColor: "normal"

        },
        //tournament 6 seats
        {
            id: 25,
            name : 'Casterly Rock',
            seats : 6,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"tournament",
            cardSuit:"inverted",
            cardBack:"#0a1a75",
            roomBackground: "5",
            roomColor: "#ffffff",
            feltColor: "#0a1a75",
            chipColor: "normal"

        },
        {
            id: 26,
            name : 'Terrallende',
            seats : 6,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"tournament",
            cardSuit:"inverted",
            cardBack:"#0a1a75",
            roomBackground: "6",
            roomColor: "#729751",
            feltColor: "#0a1a75",
            chipColor: "normal"

        },
        {
            id: 27,
            name : 'Moonbrook',
            seats : 6,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"tournament",
            cardSuit:"inverted",
            cardBack:"#0a1a75",
            roomBackground: "6",
            roomColor: "#1000ff",
            feltColor: "#0a1a75",
            chipColor: "normal"

        },
        {
            id: 28,
            name : 'Death Hollow',
            seats : 6,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"tournament",
            cardSuit:"inverted",
            cardBack:"#0a1a75",
            roomBackground: "2",
            roomColor: "#73727a",
            feltColor: "#0a1a75",
            chipColor: "normal"

        },
        {
            id: 29,
            name : 'Dreadfort',
            seats : 6,
            bb: 2,
            sb: 1,
            maxBuyIn: 200,
            minBuyIn: 40,
            privateTable: false,
            type:"tournament",
            cardSuit:"inverted",
            cardBack:"#0a1a75",
            roomBackground: "6",
            roomColor: "#bc2108",
            feltColor: "#0a1a75",
            chipColor: "normal"

        }
        
    ]
}